# Generated by Django 3.1.dev20200305084444 on 2020-04-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=200, null=True)),
                ('Check_In', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('Check_Out', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('Status', models.CharField(choices=[('Working', 'Working'), ('End', 'End')], max_length=100, null=True)),
                ('Attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=100, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200, null=True)),
                ('Email_Address', models.EmailField(max_length=200, null=True)),
                ('CNIC', models.CharField(max_length=200, null=True)),
                ('Phone_No', models.CharField(max_length=200, null=True)),
                ('Department', models.CharField(choices=[('Psychologist', 'Psychologist'), ('Physiotherapist', 'Physiotherapist'), ('Consultant', 'Consultant')], max_length=200, null=True)),
                ('Experience', models.CharField(choices=[('1 Year', '1 Year'), ('2 Year', '2 Year')], max_length=200, null=True)),
                ('Education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=200, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.Attendance')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.Employee')),
            ],
        ),
    ]
