# Generated by Django 3.1.dev20200305084444 on 2020-04-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='EmployeeName',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Employee_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.Employee'),
        ),
    ]
