# Generated by Django 3.1.dev20200305084444 on 2020-04-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20200418_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Any_Leave',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(choices=[('Working', 'Working'), ('End', 'End'), ('Extra Shift', 'Extra Shift'), ('On Leave', 'On Leave')], max_length=100, null=True),
        ),
    ]
