# Generated by Django 3.1.dev20200305084444 on 2020-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20200418_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Attendance_ID',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='Att_Percentage',
            field=models.IntegerField(choices=[('100%', '100%'), ('50%', '50%'), ('Less than 50%', 'Less than 50%')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='Salary',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(choices=[('Psychologist', 'Psychologist'), ('Physiotherapist', 'Physiotherapist'), ('Consultant', 'Consultant'), ('Intern', 'Intern')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Experience',
            field=models.CharField(choices=[('1 Year', '1 Year'), ('2 Year', '2 Year'), ('More than 2 Years', 'More than 2 Years')], max_length=200, null=True),
        ),
    ]
