# Generated by Django 3.1.dev20200305084444 on 2020-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20200418_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Attendance_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='Att_Percentage',
            field=models.IntegerField(choices=[('100%', '100%'), ('50%', '50%'), ('Less than 50%', 'Less than 50%')], null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='Salary',
            field=models.IntegerField(null=True),
        ),
    ]
