# Generated by Django 3.1.dev20200305084444 on 2020-04-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20200418_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Early_Going',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Late_Comming',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
    ]
