# Generated by Django 3.1.dev20200305084444 on 2020-04-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20200418_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='FullHours_Utilized',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
    ]
