# Generated by Django 3.1.dev20200305084444 on 2020-04-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_attendance_fullhours_utilized'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Time_In',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Time_Out',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='Salary',
            field=models.CharField(choices=[('Full', 'Full'), ('Deducted', 'Deducted')], max_length=100, null=True),
        ),
    ]
