# Generated by Django 3.1.dev20200305084444 on 2020-04-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_auto_20200418_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Confirm_Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='Att_Percentage',
            field=models.CharField(choices=[('100%', '100%'), ('50%', '50%'), ('Less than 50%', 'Less than 50%')], max_length=50, null=True),
        ),
    ]
