# Generated by Django 3.1.dev20200305084444 on 2020-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_auto_20200420_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Leaves', models.IntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Any_Leave',
        ),
    ]
