# Generated by Django 3.1.dev20200305084444 on 2020-04-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_auto_20200420_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavestag',
            name='Total_Leaves',
            field=models.IntegerField(null=True),
        ),
    ]
