# Generated by Django 3.1.dev20200305084444 on 2020-04-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_auto_20200420_0225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeavesTag',
            new_name='Leave',
        ),
    ]
