# Generated by Django 3.1.dev20200305084444 on 2020-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_auto_20200420_0226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Any_Leave',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('None', 'None')], max_length=100, null=True),
        ),
    ]
