# Generated by Django 3.1.dev20200305084444 on 2020-04-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_auto_20200421_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Confirm_Password',
            new_name='Designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Password',
        ),
    ]
