# Generated by Django 3.1.dev20200305084444 on 2020-04-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20200421_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Confirm_Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
