# Generated by Django 3.1.dev20200305084444 on 2020-04-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_auto_20200422_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Salary',
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_Salary', models.CharField(max_length=100, null=True)),
                ('Employee_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.Employee')),
            ],
        ),
    ]
