# Generated by Django 3.1.dev20200305084444 on 2020-04-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_auto_20200423_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='Basic_Salary',
            new_name='Salary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='Basic_Salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.Salary'),
        ),
    ]
