# Generated by Django 3.1.dev20200305084444 on 2020-04-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0021_auto_20200423_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Attendance',
            new_name='Mark_Attendance',
        ),
    ]
