# Generated by Django 3.1.dev20200305084444 on 2020-04-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0024_auto_20200424_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='Attendance',
            new_name='Mark_Attendance',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Month',
        ),
    ]
