# Generated by Django 3.1.dev20200305084444 on 2020-04-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0025_auto_20200424_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='Four_or_MoreLeave',
            field=models.DecimalField(decimal_places=50, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='Month_Year',
            field=models.DecimalField(decimal_places=50, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='Per_Day_Wage',
            field=models.DecimalField(decimal_places=50, max_digits=50, null=True),
        ),
    ]
