# Generated by Django 3.1.dev20200305084444 on 2020-04-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0026_auto_20200424_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='Month_Year',
            field=models.CharField(choices=[('January 2020', 'January 2020'), ('February 2020', 'February 2020'), ('March 2020', 'March 2020'), ('April 2020', 'April 2020'), ('May 2020', 'May 2020'), ('June 2020', 'June 2020'), ('July 2020', 'July 2020'), ('August 2020', 'August 2020'), ('September 2020', 'September'), ('October 2020', 'October 2020'), ('November 2020', 'November 2020'), ('December 2020', 'December 2020')], max_length=100, null=True),
        ),
    ]
