# Generated by Django 3.1.dev20200305084444 on 2020-04-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0027_auto_20200424_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='Four_or_MoreLeave',
        ),
        migrations.AddField(
            model_name='payroll',
            name='Four_LeaveSpent_Deduction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='Per_Day_Wage',
            field=models.IntegerField(null=True),
        ),
    ]
