# Generated by Django 3.1.dev20200305084444 on 2020-04-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0028_auto_20200424_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Username',
        ),
    ]
