# Generated by Django 3.1.dev20200305084444 on 2020-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0029_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
