# Generated by Django 3.1.dev20200305084444 on 2020-04-30 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0033_auto_20200430_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empuser',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
