# Generated by Django 3.1.dev20200305084444 on 2020-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0034_auto_20200430_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Time_In',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Time_Out',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
