# Generated by Django 3.1.dev20200305084444 on 2020-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0036_auto_20200506_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Time_In',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
