# Generated by Django 3.1.dev20200305084444 on 2020-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0037_auto_20200506_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='Final_Pay',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
