# Generated by Django 3.1.dev20200305084444 on 2020-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0038_payroll_final_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='No_of_Presents',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
